### ISSUE TITLE
Scraping scrapes wrong systems...

### ISSUE THREAD

**Issue by Kugelblitz360** [andresdelcampo/GameList_Editor#13]
So I briefly tried out updating some games, but ran into the problem that the scraper picked the wrong system. I got Atari ST screens and art for some C64 games for example. Do I need to set extra parameters? My Screenscraper credentials are correct.

**Comment by Kugelblitz360** [comment]
Two examples here. First trying an Amstrad CPC game returns the media for the Amiga version. Then trying a C64 game returns the media for the Sega Master System version.
![Clipboard Image](https://github.com/andresdelcampo/GameList_Editor/assets/61011450/388272c9-de62-44a6-8f29-8488a60d802e)
![Clipboard Image (1)](https://github.com/andresdelcampo/GameList_Editor/assets/61011450/1e48892e-e3c5-4ffa-8240-a7e89cada072)
![Clipboard Image (2)](https://github.com/andresdelcampo/GameList_Editor/assets/61011450/f6a5e804-ced3-4078-b4c8-07f0fe055922)
![Clipboard Image (3)](https://github.com/andresdelcampo/GameList_Editor/assets/61011450/f73c3d81-673c-45ef-aec7-2defd24da7ea)

**Comment by andresdelcampo** [comment]
The first game did not seem to be in the DB, but the second is, and you are right, it does not match. https://www.screenscraper.fr/gameinfos.php?gameid=36304&action=onglet&zone=gameinfosmedias 

The query itself in code seems right -it only passes ROM CRC and system ID, but maybe the systems were mismatched or maybe altered at the server... no, those still are 65 and 66 for CPC and C64... I will need to investigate a bit deeper to see what is going on. The one for CPC I could understand -it did not have it in that system and it tried a different one- but the one for C64 should have worked? I will try to get those roms -to get their CRC- and try the service API to see where the issue is -in the server or the app. Give me a few days -shouldn't take long.

**Comment by Kugelblitz360** [comment]
My only good guess would then be locale settings in Windows - my system is set to German and that might mess up date formats in the app?

**Comment by andresdelcampo** [comment]
My bad, I should not mix topics. Ok, on the scraper part... no luck on another 007 CPC alternative rom -different hash. 

But I managed to repro the C64 one... ! 

I can confirm that GameListEditor is passing the right system, and the CRC -I see no issues in the API call. Unfortunately the ScreenScraper site does not return the right info as the ROM CRC is not matching the Commodore 64 one... https://www.screenscraper.fr/rominfos.php?romid=874522 84020FA5 but 86996661 instead (52F76B5 in hex). So given that it figures out that the game is the right one, I suspect someone entered the right CRC (for C64) in the wrong system (Sega) in ScreenScraper... 

Actually, try this: https://www.screenscraper.fr/rominfos.php?romid=874522 -notice that the page says Commodore 64. Now click in Summer Games (Game Name field).... notice where you land. https://www.screenscraper.fr/gameinfos.php?gameid=960&action=onglet&zone=gameinfosroms -see which system it is... this is something to report to ScreenScraper.fr. I am afraid I cannot do much about it from the GameListEditor point of view, and I have no direct contact with the site guys. I would suggest you take it with them if interested in fixing it... I am afraid it will be case by case individually as this is strictly about the site contents.

**Comment by Kugelblitz360** [comment]
Ah, if you search by CRC you of course will run into issues on computer software, especially disk based or cartridges with integrated save, because the CRCs do change and there are MANY versions anyway. They are only useful on consoles really, the CRC lists for Home Computers are very incomplete. For these cases the scraper in Emulation Station allows a search by name (and manual input of the search string) and then shows a list of possible entries. If that is out of scope for your project, I understand and just close the request, but you might want to add a remark that scraping is by CRC only. Thank you!

**Comment by andresdelcampo** [comment]
It could be if it worked, but the funny part is that ScreenScraper had the system already as it was passed as part of the search. It knew it was a C64 ROM, not a Sega one, and it correctly identified it was Summer Games. It just made the leap to Sega for some strange reason... While changing the scraper functionality is not in scope at the moment, I will keep it in mind if I get to expand the Scraper. It is not so much "my project", I kind of adopted it quite mature, as I liked it and I wanted to expand it a bit with video and so on and it was sadly abandoned, but Scraper to me was rather secondary -particularly massively scraping- as it is waaay too slow and there are better alternatives with other software. But when it comes to the UI and browsing the game collection and editing the gamelist, very few (none?) can beat GameListEditor :).

**Comment by Kugelblitz360** [comment]
You are right, as an Editor it is #1, followed by Batgui.
