### ISSUE TITLE
Date format problem when hashing

### ISSUE THREAD

**Issue by Kugelblitz360** [andresdelcampo/GameList_Editor#14]
When I try to get additional info on a game, apparently the format of date that the scraper in Emustation uses causes a problem. Also I get a warning that hashing the file could take some time.
<img width="321" alt="image" src="https://github.com/andresdelcampo/GameList_Editor/assets/61011450/8be5c91a-138c-4fff-bb86-5075912d3456">

**Comment by andresdelcampo** [comment]
Hmm... I may need more info on this one. 

I did try changing the date format in Windows and I did not trigger the issue. I also have a region date format of DD/MM/YYYY and had no problems parsing... so I wonder what is triggering it.

**Comment by Kugelblitz360** [comment]
Is there any way I can provide more info? Any logging?

**Comment by andresdelcampo** [comment]
Not likely, unfortunately there is not much logging in this app. I refer to more detailed repro steps -what is the date of the game when you start, where you click, and when the error happens -or maybe if it happens in other operations, etc.

**Comment by Kugelblitz360** [comment]
This seems to be related to the "Last Played" Date. If none is set, I do not get the error message.

**Comment by andresdelcampo** [comment]
That is a very good hint... how does the failing date look like in the gamelist xml? 
The normal release dates I have are stored like 
	<releasedate>19890101T000000</releasedate>
but I haven no lastplayed in my sample. It is not editable in the app from what I see, and when read it is parsed like 

      Edt_LastPlayed.Text:= FormatDateTime('dd/mm/yyyy hh:mm:ss' , ISO8601ToDate( aGame.ReleaseDate ) )

which hints that the lastplayed date should have been in ISO 8601 format. 
So it looks like the one you have is not. How did you get that lastplayed date generated?

**Comment by Kugelblitz360** [comment]
<path>./James Bond 007 - Licence to Kill.zip</path>
		<name>007: Licence to Kill</name>
		<desc>A "James Bond" action/arcade game based on the movie with the same name. Your aim is to avenge the death of Felix Leiter, who was killed by the drug baron Sanchez.

Technically the game consists of several different vertical scrolling action sequences. In each stage you must fly, drive or walk through a preset terrain. While doing that, you have to shoot enemies, avoid their shots and collect items (mainly ammunition). Some levels rely more on shooting, while others test your reflexes.</desc>
		<image>./images/James Bond 007 - Licence to Kill-image.png</image>
		<video>./videos/James Bond 007 - Licence to Kill-video.mp4</video>
		<marquee>./images/James Bond 007 - Licence to Kill-marquee.png</marquee>
		<thumbnail>./images/James Bond 007 - Licence to Kill-thumb.png</thumbnail>
		<rating>0.45</rating>
		<releasedate>19890101T000000</releasedate>
		<developer>Domark</developer>
		<publisher>Quixel</publisher>
		<genre>Action</genre>
		<players>1</players>
		<playcount>1</playcount>
		<lastplayed>20210209T135123</lastplayed>
		<md5>aed105f162e6bbf98a6b31dcbd87d1ef</md5>
		<gametime>152</gametime>
		<lang>en</lang>
	</game>

Generated by Batocera (Emulationstation fork)

**Comment by Kugelblitz360** [comment]
Generated by Batocera (EmulationStation fork)
```
		<path>./James Bond 007 - Licence to Kill.zip</path>
		<name>007: Licence to Kill</name>
		<desc>A "James Bond" action/arcade game based on the movie with the same name. Your aim is to avenge the death of Felix Leiter, who was killed by the drug baron Sanchez.

Technically the game consists of several different vertical scrolling action sequences. In each stage you must fly, drive or walk through a preset terrain. While doing that, you have to shoot enemies, avoid their shots and collect items (mainly ammunition). Some levels rely more on shooting, while others test your reflexes.</desc>
		<image>./images/James Bond 007 - Licence to Kill-image.png</image>
		<video>./videos/James Bond 007 - Licence to Kill-video.mp4</video>
		<marquee>./images/James Bond 007 - Licence to Kill-marquee.png</marquee>
		<thumbnail>./images/James Bond 007 - Licence to Kill-thumb.png</thumbnail>
		<rating>0.45</rating>
		<releasedate>19890101T000000</releasedate>
		<developer>Domark</developer>
		<publisher>Quixel</publisher>
		<genre>Action</genre>
		<players>1</players>
		<playcount>1</playcount>
		<lastplayed>20210209T135123</lastplayed>
		<md5>aed105f162e6bbf98a6b31dcbd87d1ef</md5>
		<gametime>152</gametime>
		<lang>en</lang>
	</game>

```

**Comment by Kugelblitz360** [comment]
After clicking on "More Infos"

<img width="767" alt="image" src="https://github.com/andresdelcampo/GameList_Editor/assets/61011450/e26d5913-443e-4960-8fca-047b4c021a7b">

**Comment by andresdelcampo** [comment]
Perfect repro! Thanks! On it.

**Comment by andresdelcampo** [comment]
Oh wow... it was in front of me even in this thread... I even pasted the code with the bug! It was taking the release date instead of the last played date for the conversion!. After fixing it, it no longer triggers the error for the game you passed me and shows the last played date correctly. I will be publishing a patch shortly.

**Comment by andresdelcampo** [comment]
The patch is public, as GameList Editor 2023.12. Looks like you uncovered a long living bug in the app... now squashed.

**Comment by Kugelblitz360** [comment]
THANK YOU!

**Comment by andresdelcampo** [comment]
Thank you for reporting it :). And happy new year!
