### ISSUE TITLE
Can someone help me get this going? I would like to use it but I don't know how to compile/ build it? Is there no .exe? I am on windows

### ISSUE THREAD

**Issue by wtstreetglow** [andresdelcampo/GameList_Editor#15]

**Comment by wtstreetglow** [comment]
This was my fault. I'm not very familiar with github. I didn't notice that there is a "release" section off to the right of the main page for this repo. Thank you for providing the compiled version for us that don't know how to do these kind of things (non-programmers)

**Comment by wtstreetglow** [comment]
This was my fault. I'm not very familiar with github. I didn't notice that there is a "release" section off to the right of the main page for this repo. Thank you for providing the compiled version for us that don't know how to do these kind of things (non-programmers)

**Comment by andresdelcampo** [comment]
Glad to hear you found out -apologies I could not answer earlier, these days is a bit more complicated. Hope you like it!

**Comment by wtstreetglow** [comment]
No problem. Thank you for sharing your abilities with everyone! It works excellent and the changes you made are exactly what I was needing also!!
