### ISSUE TITLE
Erreur JPEG #53?

### ISSUE THREAD

**Issue by wtstreetglow** [andresdelcampo/GameList_Editor#16]
Hello,

I am getting the subject error when I select "filter for orphans" and pretty much anytime I select anything relating to filters within the software. Is this something I may can correct on my end? Thank you for any guidance you can provide!

If you need anything from me, I may be able to help with some guidance.

**Comment by andresdelcampo** [comment]
Hi, thanks for reporting that. Maybe a full window screenshot or more detailed steps might help. I have not seen that before... I assume it was with a gamelist already loaded, for example. There has to be some detail that is triggering the issue.

**Comment by wtstreetglow** [comment]
![image](https://github.com/andresdelcampo/GameList_Editor/assets/30456018/4387be4f-2a17-47cb-b3a0-ff62065b3004)

**Comment by wtstreetglow** [comment]
In my instance the steps are, open program. Select "orphan", in "select your filter" and then the error pops up. I've started messing with it a little more and it looks like a change to anything related to the filtering will create this error.

Also, I just hit ok, in hopes to use the "delete orphans" feature even with the small issue spoken of above, and it has been going for around 4 minutes (trying to delete 700 orphans) and it is still spinning. I'm going to give it around 10 just to see what happens. It seems like the problem being spoken of above may be causing this portion to not work also.

Sorry, I don't know much about programming so just trying to provide as much info a possible?

Would you like a video?

**Comment by andresdelcampo** [comment]
Hmm... I suspect there may be an issue with the picture referred by that game. Would you mind opening the gamelist.xml file in the Nintendo directory and find the entry for that game, then check what the image tag points to? (or past the whole game entry). Also check if the picture path maps to a file in the drive -I assume it may- and check if you can open that picture with Paint?

**Comment by wtstreetglow** [comment]
That's the thing. I don't really understand how to know what game it is. Since it just says Error #53. I don't it has anything to do with the highlighted 10 yard fight

**Comment by wtstreetglow** [comment]
Just letting you know, I attached my gamelist file 2 post back (for nintendo)

**Comment by wtstreetglow** [comment]
Oh now I'm noticing some really strange stuff. It looks like nintendo is listed a bunch of times in the "select your system" dropdown. 

I apologize for just now realizing all of these different things. This was the first time I had set down to start using your extension. I am very thankful for what you have built. I just don't know how to troubleshoot it very good.

![image](https://github.com/andresdelcampo/GameList_Editor/assets/30456018/d53cb12a-19e9-447c-90da-7573e0653e30)

**Comment by andresdelcampo** [comment]
I suspect the first issue may have been an error trying to load the image for 10 yard fight. The gamelist.xml file may point to what the 10 yard fight image is supposed to be and possibly point to an existing file that may not be a correct jpg format. 

Regarding the second issue, that is probably coming from the gamelist xml themselves. They are probably having the <gamelist> <provider> <System> tag set to just Nintendo in many of them. 

Checking the gamelist... ok there is no provider set, so that might explain why multiple are Nintendo. 
I have this one for example, for C64:
	<provider>
		<System>Commodore 64</System>
		<software>Skraper</software>
		<database>ScreenScraper.fr</database>
		<web>http://www.screenscraper.fr</web>
	</provider>
![image](https://github.com/andresdelcampo/GameList_Editor/assets/33843515/bb84fb07-91f4-4d76-971b-0bb27d5dcfcc)

Try adding something like that to your gamelist.xmls and that should solve the second issue of multiple names. 

About the first issue, I can see it points to ./images/10-Yard Fight (U)-image.jpg
Does that image exist? Can you open it in Paint?

**Comment by wtstreetglow** [comment]
> I suspect the first issue may have been an error trying to load the image for 10 yard fight. The gamelist.xml file may point to what the 10 yard fight image is supposed to be and possibly point to an existing file that may not be a correct jpg format.
> 
> Regarding the second issue, that is probably coming from the gamelist xml themselves. They are probably having the tag set to just Nintendo in many of them.
> 
> Checking the gamelist... ok there is no provider set, so that might explain why multiple are Nintendo. I have this one for example, for C64: Commodore 64 Skraper ScreenScraper.fr http://www.screenscraper.fr ![image](https://private-user-images.githubusercontent.com/33843515/293589134-bb84fb07-91f4-4d76-971b-0bb27d5dcfcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTY5NjIsIm5iZiI6MTcwNDExNjY2MiwicGF0aCI6Ii8zMzg0MzUxNS8yOTM1ODkxMzQtYmI4NGZiMDctOTFmNC00ZDc2LTk3MWItMGJiMjdkNWRjZmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEzNDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxY2U2NDQ3Yjk2ODM2ZjI5Yzk4NjgwMzg3MzAxNjYwNmI3ZGJlZWNkMzNhYTY4OGFjM2M1YmVkNjU1MDNkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MRm4jn24vfOwbSzvXuK5oGAvTWEEzVg7z0Fx8XTFrww)
> 
> Try adding something like that to your gamelist.xmls and that should solve the second issue of multiple names.
> 
> About the first issue, I can see it points to ./images/10-Yard Fight (U)-image.jpg Does that image exist? Can you open it in Paint?

The below looks strange to me. It is on line 53-54.

![image](https://github.com/andresdelcampo/GameList_Editor/assets/30456018/771ca562-3644-4e5f-b7ac-301f41299966)

**Comment by andresdelcampo** [comment]
Also, before fixing the systems issue in the gamelists, make sure it is not transient -that if you reopen the app you still see multiple Nintendos.  Because it sounds as if they were fine before? Normally GameListEditor would have taken the directory name in absence of a system.

About the strange entry, I do not think that might be the problem, but you can always try to temporarily remove it to see if it changes anything. It looks like just a game missing a ton of info. Game Id is not required at all. It is just fed by the scraper to make it easier to identify in the future.

**Comment by wtstreetglow** [comment]
Ok, so it looks like everything is fine on the 10 yard fight photo. See screenshot below.

![image](https://github.com/andresdelcampo/GameList_Editor/assets/30456018/6ef09b41-d427-4822-96b3-e2e7801f3929)

**Comment by andresdelcampo** [comment]
Can you pass me the jpeg? Maybe I can reproduce the issue with that jpeg. It could still be a format issue. And it looks that way seeing that it cannot be opened in the GameList app. Maybe it is an incompatible format that needs to be converted -you can try to re-save it as JPG with Paint, for example. That might fix it if it is a JPG format issue.

**Comment by wtstreetglow** [comment]
> Also, before fixing the systems issue in the gamelists, make sure it is not transient -that if you reopen the app you still see multiple Nintendos. Because it sounds as if they were fine before? Normally GameListEditor would have taken the directory name in absence of a system.
> 
> About the strange entry, I do not think that might be the problem, but you can always try to temporarily remove it to see if it changes anything. It looks like just a game missing a ton of info. Game Id is not required at all. It is just fed by the scraper to make it easier to identify in the future.

I don't think this has ever worked exactly right. I think it did the multiple instances of nes in the old version also. Let me test the old version right quick.

**Comment by wtstreetglow** [comment]
![10-Yard Fight (U)-image](https://github.com/andresdelcampo/GameList_Editor/assets/30456018/7a5f4241-cff6-4c7b-a589-390274fb8766)

**Comment by wtstreetglow** [comment]
omg. I'm getting ready to apologize so much

**Comment by wtstreetglow** [comment]
Ok. so the system situation in the "select your system" is corrected by using YOUR version of the software. I was opening the old bad/ original version!!  I'm so sorry!!

**Comment by andresdelcampo** [comment]
I can repro the issue with that image... 
and the solution suggested works!  (open with Paint and resave as JPG with the same name and location and that fixes it :))

No need to apologize for anything. The error could have been more specific.

**Comment by wtstreetglow** [comment]
The error 53 does still exist

**Comment by andresdelcampo** [comment]
Looks like both issues are solved! :). Feel free to open more issues if you find them.

**Comment by wtstreetglow** [comment]
Oh wow, that is strange

**Comment by andresdelcampo** [comment]
Yes. It is an issue with the specific JPG you passed me. Somehow it is incompatible with GameListEditor -but if you resave it with Paint, it works fine.

**Comment by wtstreetglow** [comment]
Thank you so much @andresdelcampo. I am so sorry for the "goose chase" at the start and the error on my end using the wrong program for a bit.

**Comment by wtstreetglow** [comment]
Can you tell me how you determined the very first image had the issue? Blows my mind. How not 200 images down the list?

**Comment by andresdelcampo** [comment]
Because the program showed a JPG error and no image for 10-yard. Yet the image existed. Therefore it failed loading. I downloaded your image and switched it with one of my games, and got the exact same error. Then I tried resaving it and worked again :). 

I have passed the image for analysis to ChatGPT and got a similar result:
![image](https://github.com/andresdelcampo/GameList_Editor/assets/33843515/60a44fd2-35de-4d3a-8436-2b3f56e8ace8)

**Comment by andresdelcampo** [comment]
LOL, I kind of suspected as much... it is not a JPG, it is a PNG renamed as JPG :D

![image](https://github.com/andresdelcampo/GameList_Editor/assets/33843515/a441e8d1-6b7a-4a58-8554-92119fd5994d)

**Comment by andresdelcampo** [comment]
so your alternative fix is to rename the image to png and also the gamelist.xml reference to png as well. But I have not tested that fix. It should work though -unless the png is corrupted as well :D.

**Comment by wtstreetglow** [comment]
> Because the program showed a JPG error and no image for 10-yard. Yet the image existed. Therefore it failed loading. I downloaded your image and switched it with one of my games, and got the exact same error. Then I tried resaving it and worked again :).
> 
> I have passed the image for analysis to ChatGPT and got a similar result: ![image](https://private-user-images.githubusercontent.com/33843515/293590066-60a44fd2-35de-4d3a-8436-2b3f56e8ace8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTgwODEsIm5iZiI6MTcwNDExNzc4MSwicGF0aCI6Ii8zMzg0MzUxNS8yOTM1OTAwNjYtNjBhNDRmZDItMzVkZS00ZDNhLTg0MzYtMmIzZjU2ZThhY2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE0MDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmVhMjY4YmIzOWEwMmRlYzQwYzc1ODVhMzY3MmE5Yjk1ZjJlZDAxZjBkY2MwZjFiZjExMWVlZTAyODJmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wW_d8aZOMCgmHu_qeWB0z-oUQ2Dh4YCLSw90MezXHCs)

Haha, I'm an idiot. I didn't even realize what you just said there. haha. Thank you for this response, no I was just wandering how would I have tracked this down if this was 400 games down the list and not right in my face. bad day I believe. lol-- Just in case this were to happen on another system in the future. Thank you for being so helpful.

**Comment by andresdelcampo** [comment]
Happy to help, and happy new year :)

**Comment by wtstreetglow** [comment]
@andresdelcampo Thank you and you too!!
