### ISSUE TITLE
Feature request. (Favoriting)- No issue if you're not interested in extending functionality or just don't have the time.

### ISSUE THREAD

**Issue by wtstreetglow** [andresdelcampo/GameList_Editor#17]
Is there any chance of you adding the ability to favorite within the software? (Maybe just a checkbox on the main page that reads the existing gamelist and prechecks the box if it's already a favorite but allows the checking/ unchecking if the user would like to change the condition.

I just find it easier to favorite when working on the gameslist on the pc. I use windows retrobat on my pc as the frontend and retropie on a small arcade I built. Both programs have a little bit of an annoying process when favoriting from the frontend. When you favorite a game, it pops you to the top of the list and you have to scroll all the way back down to where you were to continue favoriting games. So this happens after each game is favorited.

Just figured I would ask and again no issue at all if you feel like it's not a very useful situation or you just don't have time. Thank you again for your past help!! Everything is working great! So happy with how you have fixed everything!

**Comment by andresdelcampo** [comment]
Favoriting games within GameListEditor is working for both a single game and multiselection. There are even several ways to do it. The most obvious one changing the game info dropdown itself (Favorite), or the other one is via the top menus. I will let you explore a bit. :)

**Comment by wtstreetglow** [comment]
I apologize for this. I didn't realize it was over there to the right as a drop down. Thank you @andresdelcampo!!
