### ISSUE TITLE
Error at start stops the app from running

### ISSUE THREAD

**Issue by 20GotoTen** [andresdelcampo/GameList_Editor#19]
Hi! Firstly this is a superb editor which I've used previously, but I now get the error "exception EOIeSysError in module Gamelisteditor.exe at 00132BC9. class not registered" when I try to run it on a newer Windows 11 pc. 

Is there a fix or workaround for this? I'd love to use it again as it's by far the best gamelist editor out there.

Thanks again

**Comment by andresdelcampo** [comment]
Hi! Yes, that is a known issue with a fix :).  It is due to missing Windows video dependencies. 
Please check https://github.com/andresdelcampo/GameList_Editor/issues/18 
That should solve it.

**Comment by andresdelcampo** [comment]
Actually, please confirm it solves the issue :). I suspect you may not have a chance to answer if I closed it.

**Comment by 20GotoTen** [comment]
Thanks for your response! I managed to find your closed issues and it had led me to another solution.

On Windows 11, I went to Control Panel / Programs & Features / Turn Windows features on or off, expanded Media Features and ticked "Windows Media Player Legacy (app)" and then it worked!

It may be a simpler fix for those like me who get the error. Thanks again!
