### ISSUE TITLE
Bulk hide/edit gamelist entries

### ISSUE THREAD

**Issue by 89carrot** [andresdelcampo/GameList_Editor#4]
Hello, thank you for continuing to support this project!

When I select multiple game entries many of the field are greyed out. It would be great to be able to bulk edit files and also hide them. This would be handy when dealing with multiple disk games etc.

Would it be possible to add this in a future release?

Thank you

**Comment by andresdelcampo** [comment]
Hi 89carrot! A pleasure, thanks for your comment.

I gave multi-editing a thought overnight. It definitely makes sense with multidisk games, but I am not sure it is used anywhere else -probably not. Multiediting is not a simple feature. But... multidisk games are always contiguous... so... how about a button to copy all the metadata and image/video from the one above (from the previous one)? (i.e. copy in disk2 all the info from disk1). It is like a full game copy / paste where you would only need to change the disk number. And you probably can still make up your mind before clicking Save changes. I can probably make that happen quite fast :) -just confirm this would fully solve the problem.

About hiding games... does Retropie/Recalbox/Batocera implement something like that? I could do some research and align the functionality. If they have a gamelist.xml tag to mark the game as hidden, I will honor it somehow. If this is something the engines do not have, I am not sure what is the advantage here as you probably would need to alter the disk numbers anyway? Let me know what you think, as I may not be fully understanding the hide games scenario.

**Comment by 89carrot** [comment]
Good Day, thank you for your quick response!

Aside from Hidden and Favourite, multi-editing wouldn't be of much use. I was just looking to use the CTRL key and select multiple games, then be able to change the hidden or favourite flag for example. Copying one to the other might help, but it seems screenscraper does pickup both entries twice so it would be of value to be able to multi-hide. Either way that would be nice to have.

For hiding the games, at least in Retrobat it does support the <hidden> gamelist flags. I suspect the others do too. If i set a game to <hidden>true</hidden>, it hides it in the front end. If I set the flag to false it shows up again. So it should be something that is possible.

Thanks again for your support of these inquiries!

**Comment by andresdelcampo** [comment]
Ok, pardon my confusion earlier. I did not realize that GameList Editor already had support for favorites and hidden as dropdowns. Interesting choice. Well, that saves me the effort to implement them as they are already there :). 

So I imagine you would be traversing the game list and choosing your favorite games or games to hide and I can see that it definitely takes time to go to the dropdown, change the value and click save, then back to the list, etc. So... what if you had "quick swap favorite" and "quick swap hide" shortcut keys? That should be a lot faster than ctrl+clicking stuff while scrolling and making sure you never click away or lose all your selection... I would just need to document it.

So I can envision that you are pressing arrow down, seeing each game, and pressing Alt+F or Alt+H (or similar) and it automatically swaps the value of favorite or hidden and saves the game all in one shortcut. You can have one hand in Alt+F and the other in arrow down. It could be blazing fast to use it that way. Well, the actual shortcut might change, as it might conflict with others probably, but you get the point. And no need to multi edit, this should be even faster.

And that is quite fast to implement. You could have it probably around this weekend :).

Any thoughts?

**Comment by 89carrot** [comment]
> So I can envision that you are pressing arrow down, seeing each game, and pressing Alt+F or Alt+H (or similar) and it automatically swaps the value of favorite or hidden and saves the game all in one shortcut. You can have one hand in Alt+F and the other in arrow down. It could be blazing fast to use it that way. Well, the actual shortcut might change, as it might conflict with others probably, but you get the point. And no need to multi edit, this should be even faster.
> 
> And that is quite fast to implement. You could have it probably around this weekend :).
> 
> Any thoughts?

That would be perfect! You're right...the CTRL+ could cause issues with losing the selection if you click elsewhere.

Thanks

**Comment by andresdelcampo** [comment]
Well... exploring the sources to add the new shortcuts shows me that the functionality you were asking for in the very beginning... was already there!!! This tool keeps surprising me! 

**If you multiselect games, the menu Actions / Selection will get enabled. It has several options including "Add to Hidden", "Remove from Hidden", "Add to Favorites" and "Remove from Favorites" which does exactly what you wanted -change them and save each of them.** It works in the version you already have!

So, at this point I am not sure I would change that functionality. It may not be as fast as the shortcut, but with the other functionality already implemented, it is probably good enough? It might add more confusion to add an extra way of doing that.

Well... if you find any issues in the tool or other features please keep communicating them and I will have a look.
Thanks!

**Comment by 89carrot** [comment]
That is great news! It will work for what I need to do. I'd say this issue is closed.

Thanks for your prompt response.
