### ISSUE TITLE
Connect to pi

### ISSUE THREAD

**Issue by fadangalini** [andresdelcampo/GameList_Editor#6]
Hi. This program looks great and just what I've been looking for. I have a mac, but found an old windows laptop to use this software. I can't work out how to connect to the Pi when clicking on 'Select folder'. I tried typing the IP address in the window that says network, but that didn't work. Any help greatly appreciated, thanks.

**Comment by andresdelcampo** [comment]
Try adding \\ in front of the IP. Or try \\RETROPIE. I doubt this is an issue with the program as nothing changed in this area and it was working. Whatever works with Windows in File Explorer should work also with Gamelist editor.
